---
title: Research
---

## Research interests

My research is focused on the analysis of genomic data in order to improve our understanding of bacterial evolution, epidemiology, ecology and pathogenicity. A key aim is to develop new bioinformatics and statistical methods that can handle the very large amounts of data made available by novel high-throughput sequencing techniques. 

Because of the interdisciplinary nature of my work, I have broad interests in a variety of subjects, including theoretical topics such as mathematical population genetics, Bayesian statistics or Monte-Carlo methods, and biological topics such as bacterial evolutionary processes or pathogen epidemiology.

I have worked on a wide range of bacterial pathogens, especially those causing healthcare associated infections (eg <em>Clostridium difficile</em> and <em>Staphylococcus aureus</em>) and gastrointestinal infections (eg <em>Salmonella enterica</em>, <em>Bacillus cereus</em>, <em>Campylobacter jejuni</em> and <em>Helicobacter pylori</em>).

## Collaborations

I collaborate with the <a href="http://www.modmedmicro.ac.uk/" >Modernising Medical Microbiology consortium</a> which brings together the University of Oxford, Public Health England, the Sanger Institute and the NHS, with the aim of revolutionising our understanding of human pathogens through the use of whole-genome sequencing technology. Three major bacterial pathogens are under particular investigation: <em>Staphylococcus aureus</em>, <em>Clostridium difficile</em> and <em>Mycobacterium tuberculosis</em>.

Other frequent collaborators include:

* <a href="http://www2.warwick.ac.uk/fac/med/staff/machtman/">Mark Achtman</a> (University of Warwick)
* <a href="https://www.imperial.ac.uk/people/c.colijn">Caroline Colijn</a> (Imperial College London)
* <a href="https://www.gov.uk/government/people/derrick-crook">Derrick Crook</a> (Public Health England)
* <a href="http://darlinglab.org">Aaron Darling</a> (University of Technology Sydney)
* <a href="http://www.sheppardlab.com/members/dfalush">Daniel Falush</a> (University of Bath)
* <a href="https://en.wikipedia.org/wiki/Jennifer_Gardy">Jennifer Gardy</a> (BC Centre for Disease Control)
* <a href="http://www.stats.bris.ac.uk/~madjl/">Dan Lawson</a> (University of Bristol)
* <a href="http://maidenlab.zoo.ox.ac.uk">Martin Maiden</a> (University of Oxford)
* <a href="https://www.gov.uk/government/organisations/public-health-england">John Paul</a> (Public Health England)
* <a href="http://genetics.emory.edu/faculty/faculty.php?facultyid=61">Tim Read </a> (Emory University)
* <a href="http://www.sheppardlab.com">Sam Sheppard</a> ( University of Bath)
* <a href="http://www.mh-hannover.de/4794.html?&amp;L=1">Sebastian Suerbaum</a> (University of Munich)
* <a href="http://www.danielwilson.me.uk">Danny Wilson</a> (University of Oxford)

